### ISSUE TITLE
[Question]  mmupnp can’t find “SONY KJ-43X8000H” deviceType Basic?

### ISSUE THREAD

**Issue by yamatakau08** [ohmae/mmupnp#39]
Could you support why mmupnp can’t find “SONY KJ-43X8000H” deviceType Basic?
Firstly SONY KJ-43X8000H has 3 deviceType.
-MediaRender,dial,Basic

UPnP Tool for Developer Ver.1.5.2 can find “SONY KJ-43X8000H” 3 deviceType,
-MediaRender
-dial
-Basic
![image](https://user-images.githubusercontent.com/13044987/161681516-e448650a-e43a-4614-93a3-e75db9759bf8.png)

The following My App’ code uses mmpunp can’t find “SONY KJ-43X8000H” deviceType Basic.

Even if tap on Reload button (R.id.btReload) and execute “cp.search()”, mmupnp can’t find “SONY KJ-43X8000H” deviceType Basic.
Add the cp.search argument “ssdp:all”, still can’t find that.

The screenshot of My App is at the bottom.
```
class DeviceList : AppCompatActivity() {

    private val cp: ControlPoint = ControlPointFactory.create().also {
        Log.d(TAG,"controlPoint create ${it}")

        it.addDiscoveryListener(discoveryListener({ deviceListUpdate() }, { deviceListUpdate() }))
        it.initialize()
        it.start()
        it.search()
    }

    private var xdevices = MutableLiveData<List<Map<String,String?>>>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_device_list)

        // List View for DeviceList
        val lvDeviceList = findViewById<ListView>(R.id.lvDeviceList)
        lvDeviceList.onItemClickListener = ListItemClickListener()

        xdevices.observe(this) { devices ->
            val from = arrayOf("friendlyName", "ipAddress", "deviceType")
            val to = intArrayOf(R.id.tvfriendlyName, R.id.tvipAddres, R.id.tvdeviceType)

            val adapter = SimpleAdapter(
                applicationContext,
                devices,
                R.layout.device_list_item,
                from,
                to
            )
            lvDeviceList.adapter = adapter
        }
    }
    private fun deviceListUpdate() {
       val devices = cp.deviceList.map { device ->
            mapOf("friendlyName" to device.friendlyName,
                "ipAddress" to device.ipAddress,
                "deviceType" to device.deviceType,
                //"baseURL" to device.baseUrl, // not ScalarWebAPI base Url
                "modelName" to device.modelName,
                "manufacture" to device.manufacture,
                "udn" to device.udn
            )
        }.sortedBy { it["friendlyName"] }

        xdevices.postValue(devices)
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
 　　　　　…
        when (item.itemId) {
           …
            R.id.btReload -> {
                cp.search()
            }
       }
        return true
    }
```
![image](https://user-images.githubusercontent.com/13044987/161681640-67ce591a-364a-4454-9b09-c22e5a27c18c.png)

**Comment by ohmae** [comment]
I don't know about the device, is there any error log? See below for log output
https://github.com/ohmae/mmupnp#debug-log-output
Or can you find it in the sample app in this repository?

**Comment by yamatakau08** [comment]
Thank you for your advice how to get mmupnp Log.

I attach the LOG which puts out mmupnp about the issue, not whole log.

I pick up the about the issues from LOG.
ControlPointIml read.
`2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: LOCATION: http://192.168.0.120:24970/sony/webapi/ssdp/dd.xml`
And dd.xml have Basic in the bottom line 2.
`2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:     <deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>`

```
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: request:
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: GET /DIALSCPD.xml HTTP/1.1
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: HOST: 192.168.0.120:24970
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: User-Agent: Linux/4.19.136-perf+ UPnP/1.0 mmupnp/3.0.0
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: Connection: keep-alive
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient:
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient:
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: response:
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: HTTP/1.1 404 Not Found
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: Connection: close
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: Date: Thu, 07 Apr 2022 00:06:19 GMT
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient: Server: FedoraCore/2 UPnP/1.0 MINT-X/1.8.1
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient:
2022-04-07 09:06:19.996 18242-18276/com.example.myavremote I/HttpClient:
2022-04-07 09:06:19.998 18242-18276/com.example.myavremote W/ControlPointImpl: loadDevice: java.io.IOException: HTTP/1.1 404 Not Found
2022-04-07 09:06:19.998 18242-18276/com.example.myavremote W/ControlPointImpl: 	at net.mm2d.upnp.HttpClient.download(HttpClient.kt:241) ... 12 more
2022-04-07 09:06:19.998 18242-18276/com.example.myavremote W/ControlPointImpl:
2022-04-07 09:06:20.000 18242-18276/com.example.myavremote I/ControlPointImpl: DeviceBuilder
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: SSDP:HTTP/1.1 200 OK
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: CACHE-CONTROL: max-age=1800
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: EXT:
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: LOCATION: http://192.168.0.120:24970/sony/webapi/ssdp/dd.xml
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: SERVER: FedoraCore/2 UPnP/1.0 MINT-X/1.8.1
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: ST: urn:schemas-sony-com:service:IRCC:1
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: USN: uuid:a0369a7b-c68b-4b08-8247-7ea79929a697::urn:schemas-sony-com:service:IRCC:1
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: DESCRIPTION:<?xml version="1.0"?>
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl: <root xmlns="urn:schemas-upnp-org:device-1-0">
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:   <specVersion>
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:     <major>1</major>
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:     <minor>0</minor>
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:   </specVersion>
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:   <device>
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:     <deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
2022-04-07 09:06:20.001 18242-18276/com.example.myavremote I/ControlPointImpl:     <friendlyName>SONY KJ-43X8000H</friendlyName>
...
```

Are the following Warning and Information but have Exception ... cause that mmupnp can't find the device "Basic" issue?
```
2022-04-07 09:06:19.998 18242-18276/com.example.myavremote W/ControlPointImpl: loadDevice: java.io.IOException: HTTP/1.1 404 Not Found
2022-04-07 09:06:19.998 18242-18276/com.example.myavremote W/ControlPointImpl: 	at net.mm2d.upnp.HttpClient.download(HttpClient.kt:241) ... 12 more
2022-04-07 09:06:19.998 18242-18276/com.example.myavremote W/ControlPointImpl:
2022-04-07 09:06:20.000 18242-18276/com.example.myavremote I/ControlPointImpl: DeviceBuilder
...
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl: DESCRIPTION:null
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl: java.io.IOException: HTTP/1.1 404 Not Found
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.HttpClient.download(HttpClient.kt:241)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.HttpClient.downloadString(HttpClient.kt:215)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.internal.parser.ServiceParser.loadDescription(ServiceParser.kt:52)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.internal.parser.DeviceParser.loadServices(DeviceParser.kt:60)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.internal.parser.DeviceParser.loadDescription(DeviceParser.kt:54)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.internal.impl.ControlPointImpl.loadDevice(ControlPointImpl.kt:155)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.internal.impl.ControlPointImpl.access$loadDevice(ControlPointImpl.kt:38)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.internal.impl.ControlPointImpl$loadDevice$1.invoke(ControlPointImpl.kt:146)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.internal.impl.ControlPointImpl$loadDevice$1.invoke(ControlPointImpl.kt:38)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at net.mm2d.upnp.internal.thread.ExecuteFunctionKt$toRunnable$1.run(ExecuteFunction.kt:19)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:     at java.lang.Thread.run(Thread.java:923)
2022-04-07 09:06:20.002 18242-18276/com.example.myavremote I/ControlPointImpl:
```

I attached the whole Log. Could you check the whole Log for more detail.
Note. D/DeviceList is my App's Log.
[SonyKJ-43X8000HBasicNotFound.log](https://github.com/ohmae/mmupnp/files/8438762/SonyKJ-43X8000HBasicNotFound.log)

**Comment by ohmae** [comment]
I agree. The cause is that the device is returning 404.
This library is designed to ignore devices for which information cannot be obtained normally. That device is ignored because one of the service descriptions cannot download.
It's a device's problem.

**Comment by yamatakau08** [comment]
I understand the device's problem? and mmupnp library specification.

But ...

Since "UPnP Tool for Develoer" can find device Type "Basic",
mmpunp also can find the device Type "Basic".

I attach the device xml file "dd.xml" which is not the same one before but has same issue.

With using this attached "dd.xml", colud you ADAPT to find "Basic" device.
Because mmupnp is very nice library and my App depends on it's functionality.

Note that dd.txt is dd.xml file, change suffix to xml when using it.
Because issue board does support xml suffix to attach.

[dd.txt](https://github.com/ohmae/mmupnp/files/8449723/dd.txt)

**Comment by ohmae** [comment]
The problem is `<SCPDURL>/DIALSCPD.xml</SCPDURL>`

**Comment by ohmae** [comment]
This looks like a DIAL.
DIAL is a protocol like UPnP, but it violates the UPnP specification.

**Comment by yamatakau08** [comment]
With your comment, I checked if curl can fetch each service's xml in device "Basic:1" xml.

DeviceType Basic:1's xml has 3 serviceType like folllwoing xml.
1. ScalarWebAPI
2. dial
3. IRCC

```
foo@hoge ~/tmp> curl http://192.168.0.32:40886/sony/webapi/ssdp/dd.xml
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
  ...
  <device>
    <deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
    ...
    <modelName>KJ-43X8500H</modelName>
    ...
<iconList>
    ...
</iconList>
    <serviceList>
      <service>
        <serviceType>urn:schemas-sony-com:service:ScalarWebAPI:1</serviceType>
        ...
        <SCPDURL>/sony/webapi/ssdp/scpd/WebApiSCPD.xml</SCPDURL>
        ...
      </service>

       <service>
           <serviceType>urn:dial-multiscreen-org:service:dial:1</serviceType>
           ...
           <SCPDURL>/DIALSCPD.xml</SCPDURL>
           ...
       </service>

      <service>
        <serviceType>urn:schemas-sony-com:service:IRCC:1</serviceType>
        ...
        <SCPDURL>http://192.168.0.32/sony/ircc/IRCCSCPD.xml</SCPDURL>
        ...
      </service>
    </serviceList>
    ...
  </device>
</root>
```

About dial service, curl NO OUTPUT means can not find DIALSCPD.xml

```
foo@hoge ~/tmp> curl http://192.168.0.32:40886/DIALSCPD.xml
foo@hoge
```

Other services, curl CAN FETCH its own xml.

I'm not familiar with upnp,but The aboeve result,
I guess that mmupnp judge this xml content is none as an error.

Could you ADAPT not to judge error or skip this kind of error.

On My app, I just only want to list up deviceType "Basic" and no need ad devices Services.

**Comment by ohmae** [comment]
That needs to be carefully considered.
It would be inconsistent with the design policy of this library, which is to find only error-free devices.

**Comment by ohmae** [comment]
It was difficult to determine, but it is true that a DIAL could result in a 404.
I have released v.3.1.4 with a change to ignore the Exception if the device type is DIAL.
While I am not yet certain that this is the right decision, I have decided to make this change because it will not affect other library users, if they use this library carefully.
https://search.maven.org/artifact/net.mm2d.mmupnp/mmupnp/3.1.4/jar

**Comment by yamatakau08** [comment]
Thank you for release.
I update the mmupnp 3.14 and build the my app.
Unfortunately, mmupnp still can't list up the following.
```
SONY KJ-43X8000H
ST: urn:schemas-upnp-org:device:Basic:1
```
I attatched the log with mmupnp 3.14 and my app screen shot.

Could you keep supporting me.
[SonyKJ-43X8000HBasicNotFoundWithmmupnpv314.log](https://github.com/ohmae/mmupnp/files/8530430/SonyKJ-43X8000HBasicNotFoundWithmmupnpv314.log)

![image](https://user-images.githubusercontent.com/13044987/164445538-dfcd634a-3e2d-4119-bd80-e896f45f9a50.png)

**Comment by ohmae** [comment]
Retry 3.1.6
https://search.maven.org/artifact/net.mm2d.mmupnp/mmupnp/3.1.6/jar
(Don't use 3.1.5 because I made a mistake...)

**Comment by yamatakau08** [comment]
Thank you so much quick response.

3.16 works fine and my app list up "Basic" device, KJ-43X8000H.

Thank yoooooou again your support.
